version: "3.9"
services:
  my_mongodb:
    image: "mongo:6.0.2"
    restart: unless-stopped
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - users-mongo:/data/db
  zookeeper:
    image: 'zookeeper:3.8.0'
    restart: unless-stopped
    environment:
      - ZOO_ADMINSERVER_ENABLED=false
    volumes:
      - users-zookeeper-data:/data
      - users-zookeeper-datalog:/datalog
  my_kafka:
    image: "bitnami/kafka:3.3.1"
    restart: unless-stopped
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://my_kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    ports:
      - "9093:9093"
    volumes:
      - users-kafka:/bitnami/kafka
    depends_on:
      - zookeeper
  users-server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - my_mongodb
      - my_kafka
volumes:
  users-mongo:
  users-zookeeper-data:
  users-zookeeper-datalog:
  users-kafka: