# This is the default config. It contains default values which are overwritten within specific profiles.
# It is however also used for when you want to run the application locally but run the infrastructure on docker.

mongodb.encrypt:
  keys:
    - version: 1
      key: hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=

spring:
  data:
    mongodb:
      uuid-representation: standard
      auto-index-creation: true
      database: faceit-users
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer